---

- name: --- Downlaod kafka-manager ----
  shell: |
    cd /opt
    wget {{general_config.url_repo}}/{{kafka_monitoring.name}}_{{kafka_monitoring.ver}}.{{kafka_monitoring.extention}}

- name: --- Create systemd kafka-manager ---
  template: src=systemd-kafka-manager.j2 dest=/etc/systemd/system/kafka-manager.service

- name: --- install kafka-manager ---
  shell: |
   cd /opt
   unzip {{kafka_monitoring.name}}_{{kafka_monitoring.ver}}.{{kafka_monitoring.extention}}
   ln -s {{kafka_monitoring.name}}_{{kafka_monitoring.ver}} kafka-manager
  ignore_errors: true 

- name: --- Setup application.conf for kafka-manager---
  template: src=application.conf.j2 dest=/opt/kafka-manager/conf/application.conf
  
- name: --- Start kafka-manager ----
  shell: |
   systemctl deamon-reload
   systemctl start kafka-manager
   
  
- name: --- open Firewalls (port 9000)---
  shell: |
   firewall-cmd --permanent --add-port=9000/tcp
   firewall-cmd --reload
  ignore_errors: true